name: Review Github Action B22

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  CI:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout SCM
      uses: actions/checkout@v4

    - name: Build IMage
      run: docker build -t alvindra/literature-backend:staging .

    - name: Build IMage
      run: docker build -t alvindra/literature-backend:staging .

    - name: Test
      run: |
        docker run -d --name test -p 5000:5000 alvindra/literature-backend:staging
        sleep 10
        curl localhost:5000

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
